name: Win fixes for cibuildwheel
on: push

concurrency:
   group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
   cancel-in-progress: true

jobs:

  build_wheels:
    runs-on: "windows-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "windows-latest"
            CIBW_BUILD: "cp39-win32"
            CIBW_ARCHS_WINDOWS: "x86"
          - os: "windows-latest"
            CIBW_BUILD: "cp39-win_amd64"
            CIBW_ARCHS_WINDOWS: "AMD64"

    env:
      CIBW_BUILD_VERBOSITY: 1
      CIBW_BUILD: ${{ matrix.CIBW_BUILD }}
      CIBW_ARCHS_LINUX:  ${{ matrix.CIBW_ARCHS_LINUX }}
      CIBW_ARCHS_WINDOWS:  ${{ matrix.CIBW_ARCHS_WINDOWS }}
      CIBW_ARCHS_MACOS:  ${{ matrix.CIBW_ARCHS_MACOS }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.MACOSX_DEPLOYMENT_TARGET }}
      CIBW_SKIP: pp*
      CIBW_TEST_SKIP: "*-win32"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1
        filter: tree:0
    
    - name: Install OpenSSL (win32)
      if: ${{ endsWith(matrix.CIBW_BUILD, 'win32') }}
      run: |
        Remove-Item -Path "C:\Program Files\OpenSSL" -Force -Recurse  
        vcpkg install openssl:x86-windows
        New-Item -Path "C:\Program Files\OpenSSL" -ItemType SymbolicLink -Value "C:\vcpkg\packages\openssl_x86-windows\"

    - uses: docker/setup-qemu-action@v3
      if: steps.cache-wheel.outputs.cache-hit != 'true' && runner.os == 'Linux'

    - uses: pypa/cibuildwheel@v2.21.3
      if: steps.cache-wheel.outputs.cache-hit != 'true'

    - uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: wheels-${{ matrix.os }}-${{ matrix.CIBW_BUILD }}

